clear
close all
%% makeGraphの上書き 実機実験の結果をプロットする関数
load("C:\Users\mykot\OneDrive - Tokyo University of Agriculture and Technology\60MATLAB_sagyou\MicroreactorSystem2_morita\data\sensor_kosyou.mat");
% load("C:\Users\mykot\OneDrive - Tokyo University of Agriculture and Technology\60MATLAB_sagyou\kato_simulation\0703_1.mat");
sensIndex=2;
plusIndex=2;
for i=1:2
    tempData{i} = data(i).other(4:end,[5,7]);
    timeData{i} = data(i).time(4:end-1);
    RefData{i} = data(i).other(4:end,[11,12]);
    inputData{i} = data(i).current(i).controlInput(4:end,[1,3]);

    plotTempData{i} = [data(1).temperature(1).sens(4:end-1,sensIndex)*1.9841, data(1).temperature(2).sens(4:end-1,sensIndex)*1.9841, data(1).temperature(3).sens(4:end-1,sensIndex),...
                        data(1).temperature(1).sens(4:end-1,sensIndex+plusIndex)*1.9841, data(1).temperature(2).sens(4:end-1,sensIndex+plusIndex)*1.9841, data(1).temperature(3).sens(4:end-1,sensIndex+plusIndex)...
                        ];%[RefData{i}, tempData{i}];
    plotInputData{i} = inputData{i};
    t{i}=transpose(timeData{i});

    debugErrorData{i} = mean(abs(tempData{i}(300:end,:) - RefData{i}(300:end,:)));
end





%% makeGraph
FILE_IS_SAVE=true;
expTitle = "each_box";
graphToolPath="C:\Users\mykot\OneDrive - Tokyo University of Agriculture and Technology\60MATLAB_sagyou\makeGraph";
addpath(graphToolPath);
DATA_DIR_PATH = "C:\Users\mykot\OneDrive - Tokyo University of Agriculture and Technology\60MATLAB_sagyou\kato_simulation\graph"; %exp 
OUT_DIR_PATH = "C:\Users\mykot\OneDrive - Tokyo University of Agriculture and Technology\40発表ゼミ\jisaku\figure\2025_10_24\";

for i=1:1
    TEMPERATURE_GRAPH_TITLE{i} = "Box"+ string(i) +"temperature " + expTitle;
    TEMPERATURE_LINE_NAME{i} = ["$T_{a_2}$(BOX3)","$T_{a_2}$(BOX2)","$T_{a_2}$(BOX1)","$T_{a_4}$(BOX3)","$T_{a_4}$(BOX2)","$T_{a_4}$(BOX1)"];
    TEMPERATURE_LINE_WIDTH{i} = [2,2,2,2,2,2];
    TEMPERATURE_LABEL_NAME{i} = ["Time [$\mathrm{s}]$","Temperature [$^{\circ}\mathrm{C}]$"];
    TEMPERATURE_LINE_STYLE{i} = ["-","-","-","-","-","-"];

    CONTROLINPUT_GRAPH_TITLE{i} = "Box"+ string(i) + "controlInput " + expTitle;
    CONTROLINPUT_LINE_NAME{i} = ["$i_1$","$i_3$"];
    CONTROLINPUT_LABEL_NAME{i} = ["Time [$\mathrm{s}]$","Current [$\mathrm{A}$]"];

    makeGraph(t{i}',plotTempData{i}, ...
                    "lineName",TEMPERATURE_LINE_NAME{i}, ...
                    "lineStyle",TEMPERATURE_LINE_STYLE{i}, ...
                    "lineWidth",TEMPERATURE_LINE_WIDTH{i}, ...
                    "labelName",TEMPERATURE_LABEL_NAME{i}, ...
                    "graphName",TEMPERATURE_GRAPH_TITLE{i}, ...
                     "location","east",...
                    "yLimit",[24 31.0],...
                    "isSave",FILE_IS_SAVE,"outDir",OUT_DIR_PATH, ...
                    "fontSize",15,"LabelFontSize",30,"saveFileExt","png");

    % %制御入力
    % makeGraph(t{i}',plotInputData{i} , ...
    %                     "lineName",CONTROLINPUT_LINE_NAME{i}, ...
    %                     "lineWidth",[1,1,1,1], ...
    %                     "labelName",CONTROLINPUT_LABEL_NAME{i}, ...
    %                     "yLimit",[-0.2,1.8],...
    %                     "location","northwest",...
    %                     "graphName",CONTROLINPUT_GRAPH_TITLE{i}, ...
    %                     "isSave",FILE_IS_SAVE,"outDir",OUT_DIR_PATH, ...
    %                     "fontSize",21,"LabelFontSize",30,"saveFileExt","png");


end


% %温度
% makeGraph(t',plotTempData, ...
%                     "lineName",TEMPERATURE_LINE_NAME, ...
%                     "lineStyle",TEMPERATURE_LINE_STYLE, ...
%                     "lineWidth",TEMPERATURE_LINE_WIDTH, ...
%                     "labelName",TEMPERATURE_LABEL_NAME, ...
%                     "graphName",TEMPERATURE_GRAPH_TITLE, ...
%                     "lineWidth",[1,1,1,1], ..."yLimit",[22.4 27.5],...
%                     "isSave",FILE_IS_SAVE,"outDir",OUT_DIR_PATH, ...
%                     "fontSize",20,"LabelFontSize",30,"saveFileExt","jpg");
% %制御入力
% makeGraph(t',plotInputData , ...
%                     "lineName",CONTROLINPUT_LINE_NAME, ...
%                     "lineWidth",[1,1,1,1], ...
%                     "labelName",CONTROLINPUT_LABEL_NAME, ..."yLimit",[-0.8,1.6],...
%                     "location","southwest",...
%                     "graphName",CONTROLINPUT_GRAPH_TITLE, ...
%                     "isSave",FILE_IS_SAVE,"outDir",OUT_DIR_PATH, ...
%                     "fontSize",20,"LabelFontSize",30,"saveFileExt","jpg");















